### ISSUE TITLE
Identify best way to incorporate colleen's notebook into databook

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#108]
This would be an extensive task. Should probably wait until after January to worry about it.

**Comment by jeromelecoq** [comment]
@rcpeene to schedule a meeting with Colleen after the new year

**Comment by jeromelecoq** [comment]
Scheduled for Tue Jan 10

**Comment by jeromelecoq** [comment]
We talked about 
- Integrating her figures into the repo. Colleen kindly agreed to contributed simplified code to our book. 
She will modify (mostly simplify) probably 2 figures (the first of her paper) and one chosen analysis figure. 
We will link to the rest of the code in the notebook. 

- Metadata: Colleen discussed her excel table on a separate repo. Ahad will look into adding flexible columns on data portal so that we can integrate more things. We will also look into using the CLI to commit tags to datasets. And Carter will integrate a script to query NWB files broadly.
