### ISSUE TITLE
Make book interactive with Thebe

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#13]
[This](https://jupyterbook.org/en/stable/interactive/thebe.html) page describes how we could possibly make the jupyter book interactive within user's browsers using a binder kernel. Because this relies on binder, which we cannot test until the page is deployed, I think we should wait until the book is publically deployed to try and get this working.

**Comment by rcpeene** [comment]
Will try to get this working once #23 is finished.

**Comment by jeromelecoq** [comment]
Carter has some usability concerns. it is slow to start binder.

**Comment by rcpeene** [comment]
Thebe is successful with our deployment. I will adjust some things to make notebooks compatible with the way the Thebe kernel manages files, discussed in issue #51. We will have to make any further adjustments as we go.

**Comment by rcpeene** [comment]
Awaiting review from @Ahad-Allen and @jeromelecoq

**Comment by jeromelecoq** [comment]
I think the tool is functional provided binder manages to start. For me this starting was a bit slow initially (tens of minute) and somehow it became more responsive at some point. 

I could not replicate any full notebook because of the path issues mentioned in #57. 

Otherwise, I think for usability of the datebook, it is essential that a pre-computed version of the cell is visible. Forcing the user to launch every cell is going to make the book in practice unusable as any reader will have to wait for Binder to start. 

Thebe is great for diving deeper into the code and changing some variable but I suspect many readers will just read with compute. 

In addition compute is expensive and will not scale to 1000s of readers.

**Comment by rcpeene** [comment]
If binder already has a docker container setup, it should not be a long wait. I intend to ensure the docker container is rebuilt each time I push to main. I don't think they will have to wait for binder to start.

The last point is true. I wonder what binder's limitations are.
