### ISSUE TITLE
Make notebook to access NWB metrics across a dandiset and make a table from it.

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/openscope_databook#135]
We want to make a notebook in the `Basics` chapter which demonstrates the ability to make a table of the sessions in the dandiset and useful metadata about them, including filepath, date/time, session length, mouse sex age and genotype, and number of units recorded.

**Comment by rcpeene** [comment]
I've made this notebook. It includes the properties listed above as well as file size, file identifier, the list of probes, and stimulus types.

**Comment by rcpeene** [comment]
Unfortunately, since it takes about 3 minutes to open each file to pull the relevant information, all sessions in a dandiset can take dozens of minutes. After discussion we've decided this is acceptable. The notebook also has a cell demonstrating using pandas row selection syntax and then a cell which downloads all selected sessions.

**Comment by rcpeene** [comment]
PR made #138
