### ISSUE TITLE
Make optotagging notebook

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/openscope_databook#162]
We want a notebook that identifies optotagged cells.

**Comment by jeromelecoq** [comment]
Can you link the PR here

**Comment by jeromelecoq** [comment]
This is very good. The only comment I have is to consider that some neurons have a high baseline firing rate so it is harder to see what happens when otto-tagging starts. 
I would create a second plot that implements a Zscore using the pre-stim period as a baseline to measure the variance. 

Happy to discuss this in more depth
