### ISSUE TITLE
Cell matching notebook seems to fail test on GitHub

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/openscope_databook#217]

**Comment by rcpeene** [comment]
As can be seen in [this failed test](https://github.com/AllenInstitute/openscope_databook/actions/runs/4942369344) (and a dozen or so preceding it, the cell matching notebook fails our current pytest runs on github. The error yield `output.json: file not found`. 

For context, the cell matching notebook generates a file called `input.json`, and then uses `!` syntax to run the shell command for nway matching `!python -m nway.nway_matching --input_json input.json --output_json "./output.json" --output_dir matching_output` which is supposed to output a file called 'output.json'. The following cell attempts to open `output.json`, which is where the pytest fails.

This works locally, and I see the file appear. When running on Github's Ubuntu runner, it fails. Relevant details I discovered after much fiddling:
- The output of the nway command cell does print "wrote output.json" as its last print output.
- This only started failing within the last few weeks. Rerunning old tests (with the latest ubuntu runner) on our older code did not fail.
- I modified the cell matching notebook to print out the relevant directories after running the nway command, and no such `output.json` was found.
- No such problems occur when running the pytest suite on my local windows machine
- The only changes I've made to `dev` since the passing tests were changes to the way our environment was setup. I created our 'databook_utils' package, reduced requirements.txt to just our direct dependencies, and added a setup.py file to setup the environment with the package. After modifying the cell matching notebook to use our old requirements installation and a new github workflow to test only this notebook with the old environment setup, it still failed. 
- Adding a 200 ms sleep period after the command cell does make the tests pass. Eureka! It must be some kind of concurrency issue?
- However that doesn't explain why older tests succeed, and why they suddenly stopped suceeding, and why they stills suceed locally but not on github's Ubuntu runner.

**Comment by rcpeene** [comment]
I discovered that the problem would occur when the test installed the environment with the new method (using setup.py) `pip install -e .`, but wouldn't occur if the test installed with the old method `pip install -r requirements.txt`. The problem is, we rely on the new method in order to use the `dandi_utils` package that is included in the repo now.

I am unsure _why_ exactly this causes nway matching to fail in the way it does, where the file `output.json` is not found (but not on Windows). It must be something relating to how the nway matching package is installed on different machines.

**Comment by rcpeene** [comment]
The working solution is to have the tests employ _both_ installation methods mentioned above.
