### ISSUE TITLE
bug in stimulus table in NWB file

### ISSUE THREAD

**Issue by katrinaager** [AllenInstitute/openscope_databook#269]
file affected: (could be more files than this)
dandiset_id = "000036"
dandi_filepath = "sub-389014/sub-389014_ses-20180705T152908_behavior+image+ophys.nwb"

When searching through the stimulus table, there is an error in the stop time for the last frame of each movie for each stimulus type . The last frame for each stimulus is typically 899. 

example:
start time, stop time, frame number, stimulus type
44995,794.1610973086914,794.1777296622873,898,snake
44996,794.1777296622873,794.194433401875,898,snake
44997,794.194433401875,794.2110988153851,899,snake
**44998,794.2110988153851,968.3683785639711,899,snake**
44999,798.2310351121538,798.2477136911308,0,mouse_montage_1
45000,798.2477136911308,798.2643951957413,0,mouse_montage_1

The line that is causing the bug is bolded. The stop time for the last line of the last frame in each stimulus is actually the start time of the next time the visual stimulus is shown. Here is the first line of the next time the "snake" stimulus is shown. 

53999,968.3683785639711,968.3850609462949,0,snake

The start time of this stimulus aligns with the stop time of the last frame from the previous time the stimulus was shown. I am not sure if the last time should be erased all together or if it is showing the improper value for the stop time.

**Comment by jeromelecoq** [comment]
@rcpeene to confirm if the problem is in the file or notebook

**Comment by rcpeene** [comment]
This error stems from the function I use to convert the various stim objects to a table. Here are the steps this function follows
`
1. initial empty unsorted list of table rows
2. for each stim object in the stimulus section: run steps 3-4
3. iterate over this stim's timestamps and frames arrays at the same time, creating a "labled timestamp row" from the current frame, the current time, and the **next** time
4. append labeled row to table rows
5. sort table rows by start time
`

The problem arises because the various stimulus timestamps arrays are not necessarily continous. So when we take the _next_ stim timestamp (mentioned in step three) for some stimulus A, we may either be taking the actual next timestamp of stim A, or a different stimulus object may then occur, stimulus B, before the next timestamp of stim A occurs. Here is a plot of the diffs between one such stimulus type's timestamps to demonstrate my meaning.

![image](https://github.com/AllenInstitute/openscope_databook/assets/23059582/df968947-ff37-4592-8aa5-57bb6d63c52d)

I'm thinking the best solution would be to not included a `stop time` in the resulting table at all. 
- Because it is slightly deceptive:
The stimulus objects don't _actually_ include stop times. All the stop times are just presumed to be equal to the following entry's start time

- Because there's no good practice way to determine this:
There is a way; instead of making the stop_times, column before sorting, we can just go through and create a stop times column based on every entry's following start time. But this would basically create redundant data, and reminds us again of problem A.

**Comment by jeromelecoq** [comment]
I am not sure I followed. Could the problem be that the list of rows are not sorted by timestamps before the for loop? 

The end of any row should be the start of the next row unless the timestamps are not sorted and as a result you get this problem?

**Comment by rcpeene** [comment]
This code is not even necessary anymore. Issue closed!
